Leave the rest of file checks

diff --git a/orb/jobs/@drupal.yml b/orb/jobs/@drupal.yml
--- a/orb/jobs/@drupal.yml
+++ b/orb/jobs/@drupal.yml
@@ -61,6 +61,30 @@ drupal-validate:
         install-dev-dependencies: true
     - phpcs
     - grumphp
+    - run:
+        name: Silta basic checks
+        command: |
+          files=(
+            silta/silta.yml
+            silta/silta-prod.yml
+            silta/nginx.Dockerfile
+            silta/php.Dockerfile
+            silta/shell.Dockerfile
+          )
+
+          for file in "${files[@]}"; do
+            if [ -f "$file" ]; then
+              echo "✅ $file is present"
+            else
+              echo "❌ $file is missing from the repository."
+              exit 1
+            fi
+          done
+
+          if grep "drush.*8" composer.json; then
+            echo "❌ Silta is not compatible with drush 8."
+          fi
+
     - steps: <<parameters.post-validation>>
 
 drupal-build-deploy: &drupal-build-deploy
