Resolve project name by repository url

diff --git a/orb/jobs/@lagoon.yml b/orb/jobs/@lagoon.yml
--- a/orb/jobs/@lagoon.yml
+++ b/orb/jobs/@lagoon.yml
@@ -31,23 +31,26 @@ lagoon-trigger-deployment:
     - run:
         name: Lagoon deployment
         command: |
+          # Resolve project name by git url
+          LAGOON_PROJECT_NAME=$(lagoon raw --raw "query { projectByGitUrl(gitUrl: \"${CIRCLE_REPOSITORY_URL}\") { name }}" | jq -r '.projectByGitUrl.name')
+
           # Trigger a deployment in Lagoon
-          BUILD_ID=$(lagoon deploy branch \
-            --project ${CIRCLE_PROJECT_REPONAME,,} \
+          LAGOON_BUILD_ID=$(lagoon deploy branch \
+            --project ${LAGOON_PROJECT_NAME} \
             --branch ${CIRCLE_BRANCH} \
             --branch-ref ${CIRCLE_SHA1} \
             --environment ${CIRCLE_BRANCH} \
             --returndata \
             --output-json \
             --force | jq -r '.result')
-          echo "BUILD_ID: $BUILD_ID"
+          echo "BUILD_ID: ${LAGOON_BUILD_ID}"
           
           # Create the deployment link
-          PROJECT_ID=$(lagoon raw --raw "query { projectByName(name: \"${CIRCLE_PROJECT_REPONAME,,}\") { id } }" | jq -r '.projectByName.id')
-          ENVIRONMENT_NAMESPACE=$(lagoon raw --raw "query { environmentByName(project: ${PROJECT_ID}, name: \"${CIRCLE_BRANCH}\") { kubernetesNamespaceName } }" | jq -r '.environmentByName.kubernetesNamespaceName')
-          echo "Deployment url: ${LAGOON_UI}/projects/${CIRCLE_PROJECT_REPONAME,,}/${ENVIRONMENT_NAMESPACE}/deployments/$BUILD_ID"
+          LAGOON_PROJECT_ID=$(lagoon raw --raw "query { projectByName(name: \"${LAGOON_PROJECT_NAME}\") { id } }" | jq -r '.projectByName.id')
+          LAGOON_ENVIRONMENT_NAMESPACE=$(lagoon raw --raw "query { environmentByName(project: ${LAGOON_PROJECT_ID}, name: \"${CIRCLE_BRANCH}\") { kubernetesNamespaceName } }" | jq -r '.environmentByName.kubernetesNamespaceName')
+          echo "Deployment url: ${LAGOON_UI}/projects/${LAGOON_PROJECT_NAME}/${LAGOON_ENVIRONMENT_NAMESPACE}/deployments/${LAGOON_BUILD_ID}"
 
-          if [ "$BUILD_ID" = "null" ]; then
+          if [ "${LAGOON_BUILD_ID}" = "null" ]; then
             echo "Build failed"
             exit 1
           fi
@@ -57,11 +60,20 @@ lagoon-trigger-deployment:
           START_TIME=$(date +%s)
           
           while true; do
-            STATUS=$(lagoon get deployment \
-              --name $BUILD_ID \
-              --project ${CIRCLE_PROJECT_REPONAME,,} \
+            STATUS_RAW=$(lagoon get deployment \
+              --name ${LAGOON_BUILD_ID} \
+              --project ${LAGOON_PROJECT_NAME} \
               --environment ${CIRCLE_BRANCH} \
-              --output-json | jq -r '.data[].status')
+              --output-json)
+            
+            # Authentication token can expire and lagoon-cli will return error instead of JSON.
+            # Check if the response is valid JSON. 
+            if ! echo "$STATUS_RAW" | jq -e . > /dev/null 2>&1; then
+              echo "Error: Failed to parse lagoon response, see lagoon ui for more details"
+              exit 1
+            fi
+
+            STATUS=$(echo "$STATUS_RAW" | jq -r '.data[].status')
             echo "STATUS: $STATUS"
             
             if [ "$STATUS" = "complete" ]; then
@@ -69,7 +81,7 @@ lagoon-trigger-deployment:
               break
             elif [ "$STATUS" = "failed" ]; then
               echo "Build failed"
-              lagoon get deployment --name $BUILD_ID --project ${CIRCLE_PROJECT_REPONAME,,} --environment ${CIRCLE_BRANCH} --logs
+              lagoon get deployment --name ${LAGOON_BUILD_ID} --project ${LAGOON_PROJECT_NAME} --environment ${CIRCLE_BRANCH} --logs
               exit 1
             fi
             
@@ -78,7 +90,7 @@ lagoon-trigger-deployment:
             
             if [ "$ELAPSED_TIME" -ge "$TIMEOUT" ]; then
               echo "Build timed out after <<parameters.timeout>> minutes"
-              lagoon get deployment --name $BUILD_ID --project ${CIRCLE_PROJECT_REPONAME,,} --environment ${CIRCLE_BRANCH} --logs
+              lagoon get deployment --name ${LAGOON_BUILD_ID} --project ${LAGOON_PROJECT_NAME} --environment ${CIRCLE_BRANCH} --logs
               exit 1
             fi
             
@@ -87,5 +99,5 @@ lagoon-trigger-deployment:
           done
 
           # get the deployment logs
-          lagoon get deployment --name $BUILD_ID --project ${CIRCLE_PROJECT_REPONAME,,} --environment ${CIRCLE_BRANCH} --logs
+          lagoon get deployment --name ${LAGOON_BUILD_ID} --project ${LAGOON_PROJECT_NAME} --environment ${CIRCLE_BRANCH} --logs
 
