return codes

diff --git a/orb/commands/@drupal.yml b/orb/commands/@drupal.yml
--- a/orb/commands/@drupal.yml
+++ b/orb/commands/@drupal.yml
@@ -106,12 +106,13 @@ drupal-helm-deploy:
           #Detect pods in FAILED state
           function failing_pods() {
             failed_pods=$(kubectl get pod -l "release=$RELEASE_NAME" -n "$NAMESPACE" --no-headers | grep -Ev '([0-9]+)/\1' | grep -Eo '^[^ ]+'c)
-
-          if [[ ! -z "$failed_pods" ]] ; then
-            echo "Failing pods:"
-            echo "$failed_pods"
-          fi
-
+            echo "failed pods function"
+            if [[ ! -z "$failed_pods" ]] ; then
+              echo "Failing pods:"
+              echo "$failed_pods"
+              return 1
+            fi
+            return 0
           }
           
           # Delete existing jobs to prevent getting wrong log output
@@ -177,6 +178,9 @@ drupal-helm-deploy:
               LOGS_SHOWN=true
             fi
 
+            if [ failing_pods -ne 0 ]; then
+              exit $?
+            fi
             # Helm command is complete.
             if ! ps -p "$pid" > /dev/null; then
               if grep -q BackoffLimitExceeded helm-output.log ; then
