Run helm install in the background so we can show live deployment logs.

diff --git a/orb/commands/@drupal.yml b/orb/commands/@drupal.yml
--- a/orb/commands/@drupal.yml
+++ b/orb/commands/@drupal.yml
@@ -102,6 +102,9 @@ drupal-helm-deploy:
         name: Deploy helm release
         no_output_timeout: "15m"
         command: |
+          # Delete existing jobs to prevent getting wrong log output
+          kubectl delete job "$RELEASE_NAME-post-release" -n "$NAMESPACE" --ignore-not-found > /dev/null
+
           # Disable reference data if the required volume is not present.
           reference_volume=$(kubectl get pv | grep --extended-regexp "$NAMESPACE/.*-reference-data") || true
           reference_data_override=''
@@ -127,7 +130,7 @@ drupal-helm-deploy:
             version="--version <<parameters.chart_version>>"
           fi
 
-          output=$((helm upgrade --install "$RELEASE_NAME" '<<parameters.chart_name>>' \
+          helm upgrade --install "$RELEASE_NAME" '<<parameters.chart_name>>' \
             --repo '<<parameters.chart_repository>>' \
             $version \
             --cleanup-on-fail \
@@ -145,22 +148,41 @@ drupal-helm-deploy:
             $reference_data_override \
             --namespace="$NAMESPACE" \
             --values '<<parameters.silta_config>>' \
-            --timeout 15m) 2>&1) || EXIT_CODE=$?
+            --timeout 15m &> helm-output.log &
+          pid=$!
 
-          if [[ $output == *"BackoffLimitExceeded"* ]]; then
-            # Don't show BackoffLimitExceeded, it confuses everyone.
-            echo "The post-release job failed, see log output in the next step below."
-          else
-            echo "$output"
-          fi
+          echo -n "Waiting for containers to start"
 
-          exit $EXIT_CODE
+          TIME_WAITING=0
+          while true; do
+            if kubectl get pod -l job-name="$RELEASE_NAME-post-release" -n "$NAMESPACE" --ignore-not-found | grep  -qE "Running|Completed"; then
+              echo ""
+              echo "Deployment log:"
+              kubectl logs "job/$RELEASE_NAME-post-release" -n "$NAMESPACE" -f --timestamps=true
+            fi
 
-    - run:
-        name: Deployment log
-        when: always
-        command: |
-          kubectl logs "job/$RELEASE_NAME-post-release" -n "$NAMESPACE" -f --timestamps=true
+            # Helm command is complete.
+            if ! ps -p "$pid" > /dev/null; then
+              if grep -q BackoffLimitExceeded helm-output.log ; then
+                # Don't show BackoffLimitExceeded, it confuses everyone.
+                echo "The post-release job failed, see log output above."
+              else
+                echo "Helm output:"
+                cat helm-output.log
+              fi
+              wait $pid
+              break
+            fi
+
+            if [ $TIME_WAITING -gt 120 ]; then
+              echo "Timeout waiting for resources."
+              exit 1
+            fi
+
+            echo -n "."
+            sleep 5
+            TIME_WAITING=$((TIME_WAITING+5))
+          done
 
     - run:
         name: Wait for resources to be ready
